config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'trails#index'
  
  resources :trails

  post '/trails/create' => 'trails#create_api'

  get '/trails/user/:id' => 'trails#show_api'

  get '/trails' => 'trails#index_api'

  post '/user/new' => 'users#new_api'

end

app/models/trail.rb
class Trail < ActiveRecord::Base
  has_and_belongs_to_many :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_and_belongs_to_many :trails
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  respond_to :json

  def index
    @trail = Trail.all.order('created_at DESC')
  end

  def index
    @trail = Trail.all

    respond_to do |format|
      format.html
      format.json { render :json => @trail.to_json }
    end
  end


  def new
    @trail = current_user.trails.build
  end

  def create
    @trail = current_user.trails.build(trail_params)
    
    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: "Trail was sucessfully created." }
        format.json { render :show, status: :created, location: @trail }
        if current_user
          @trail.user << current_user
        end
      else 
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unpocessable_entity }
      end
    end
  end

  def create_api
    @user = User.find(params[:id])
    @trail = Trail.create(:trail_name => params[:trail_name], :trail_info => params[:trail_info], :lat_lon => params[:lat_lon])
    @trail.user << @user
    render :json => @trail
  end

  def show
    @trail = Trail.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @trail.to_json }
    end
  end

  def show_api
    @user = User.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @user.trails.to_json }
    end
  end

  private
    def trail_params
      params.require(:trail).permit(:trail_name, :trail_info, :id, :lat_lon)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  respond_to :json

  def new_api
    render :json => User.where(["email = ?", params[:email]])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pioneer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/trails/index.html.erb
<h1>This is the Trails index.html.erb page.</h1>

<%= @trail.each do |trail| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to trail.trail_name, trail %></h2>
    <p class="date"><%= trail.created_at.strftime("%B, %d, %Y") %></p>
  </div>  
<% end %>

app/views/trails/new.html.erb
<h1>Create a new Trail</h1>

<%= form_for :trail, url: trails_path do |f| %>
  <p>
    <%= f.label :trail_name %></br>
    <%= f.text_field :trail_name %> </br>
  </p>
  <p>
    <%= f.label :trail_info  %></br>
    <%= f.text_area :trail_info %></br>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/trails/show.html.erb
<h1 class="title">
  <%= @trail.trail_name %>
</h1>

<p class="date">
  Created <%= time_ago_in_words(@trail.created_at) %> ago
</p>

<p class="trail_info">
  <%= @trail.trail_info %>
</p>